acaloiaro/neoq

- README.md
- examples/add_future_postgres_job/main.go
- examples/add_job_with_custom_concurrency/main.go
- examples/add_periodic_jobs/main.go
- examples/listen_for_jobs/main.go
- go.mod
- go.sum
- memory_backend.go
- memory_backend_test.go
- neoq.go
- neoq_test.go
- postgres_backend.go
Add an in-memory backend to support use cases that don't require queue durability
> Add in-memory backend

- memory_backend.go
- postgres_backend.go
- postgres_backend_test.go
- Store context cancelFuncs to be called during Shutdown()
- This ensures the resources are released when neoq is shut down.
Co-authored-by: Juan C. Müller <jcmuller@users.noreply.github.com>
> Add Shutdown() functionality

- .github/workflows/todo_to_issue_manual.yml
- memory_backend.go
- neoq.go
- postgres_backend.go
- Make future job check interval configurable in MemBackend (fixes #11)
- Make interval of time for which jobs are dedicated a goroutine use a default in MemBackend (fixes #12)
- Make future job check interval configurable in PgBackend (fixes #18)
- Make interval of time for which jobs are dedicated a goroutine use a default in PgBackend (fixes #19)
> Make future job check interval configurable

- .goreleaser.yaml
- backends/postgres/postgres_backend.go
Packages `pq` and `pgx` allow different connection string parameters. Since `pgx` is neoq's primary SQL library, but migrations use `pq`, we had to ensure that pgx connection parameters do not get passed to the pq library when running migrations.
This issue was introduced in version `0.20.0`.
> fix: Incorrectly passing pgx connections params to pq

- backends/postgres/postgres_backend.go
When neoq is embedded in apps already use golang-migrate, they would both attempt to use the `schema_migrations` table for migrations.
This commit moves neoq to its own `neoq_schema_migrations` table so as not to clash with other golang-migrate users.
> fix: Use neoq-specific schema migrations able

- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
This reverts commit bc8df98894358f7f774ea0cd4e168559c29c31e1.
This commit was totally wrong about the motivations for holding transactions throught the duration of jobs.
Ths is an embarrassing mistake because it is the crux of the entire Postgres backend. Transactions must be held while jobs are being processed because `FOR UPDATE` requires the transaction that issued the `SELECT * FOR UPDATE ...` query to remain open to hold the lock (https://www.postgresql.org/docs/current/explicit-locking.html#LOCKING-ROWS)
The reverted commit allowed jobs to be picked up by multiple workers.
> fix: Revert "feat: Hold connections and transactions for less time"

- Makefile
`go vet` was missing the `testing` tag necessary to build some of the tests.
Fixes #71
> fix: Bare 'make' fails due to `go vet`

- .github/workflows/test.yml
- backends/postgres/postgres_backend_test.go
This test is to provide a minimal proof that jobs can be consumed by
multiple workers and in a way can only be consumed once. If the
execCount does not match the expected count then this test will fail
because either too many jobs were executed (like one executing twice) or
a job was dropped when it should not have been.
---
I used a waitgroup for this since I want to make sure multiple jobs complete on their own time and in any order. But a
waitgroup removes any natural timeout handling and instead forces the go test process to handle timeouts instead. This
might not be ideal but would only happen when there was such a significant change to the PG backend that a job does not
get processed for some reason?
> chore(test): Adding a test for multiple consumers with the pg backend.

- .github/workflows/test.yml
- backends/postgres/migrations/20230928141356_create-new-job-trigger.down.sql
- backends/postgres/migrations/20230928141356_create-new-job-trigger.up.sql
- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
Previously, new, non-future jobs were announced by executing `NOTIFY` in Go code. Triggers are much better suited for this, and reduces neoq complexity by allowing PG to perform notification work for most jobs.
"Future" jobs continue to use the `announceJob` method on a timer.
> feat: Announce jobs using PG trigger

- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
When multiple nodes were participating as workers and a cron job was to
be enqueued, all nodes would attempt to enqueue it at the same time. As
a result all but one node would successfully enqueue the job and the
other nodes would log a message about a duplicate job. In any other
scenario this would be a log that would be good to surface, but it is
not a significant error message here as the job was still enqueued
properly.
Resolves #76
---
@acaloiaro Thoughts on testing this? I could add a test for just a multi node cron job in general and assert that it is
only performed once with multiple workers. But actually asserting that the log is not shown anymore doesn't seem like a
useful test? Let me know what your thoughts are.
> fix(pg): Fixed error logs for multi node cron jobs.

- backends/postgres/postgres_backend_test.go
Since these values are being written in a separate go routine, it is
possible for a datarace to happen since we are reading them
unatomically. This just makes it so that both the reads ands writes are
done atomically.
Resolves #76
> fix(pg): Fixed data race conditions in unit tests

- backends/postgres/postgres_backend.go
I want to be able to know what job a log message is in regards to, so
this adds the queue to all of the log messages where its available. It
also makes some of the `error` logs more consistent with each other.
> chore(log): Make logging consistent and make sure queue is logged.

- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
When the queue name is uppercase, the listener will never receive the
notification when the job is enqueued. This is done specifically with
the enqueuer and consumer being separate neoq instances (server A kicks
off a job, server B is listening to perform the work).
> fix(pg): Fixed bug with upper-case channel names.

- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
> fix: #98 retries can be picked up by wrong handler

- backends/memory/memory_backend.go
- backends/postgres/postgres_backend.go
- backends/redis/redis_backend.go
- backends/redis/redis_backend_test.go
- neoq_test.go
This is another logging change to make everything consistent. Log
key-value pairs are now done via slog's Attr format based on the notes
at the tail end here: https://go.dev/blog/slog
While this might be a more opinionated change, I see one major benefit.
If the user of the library is wrapping the logging with their own logger
that they are using (zap, logrus or any else) they would have to parse
both the alternating key value pairs and the Attr structs. By only using
the Attr structs the user would only need to handle that one object type
now in their own logging layer; hopefully making integration easier for
them to have consistent logs.
---
I'm opening this specifically because I'm using logrus for my application and I found that it was unnecessarily
complicated to try to convert both …
> chore(log): Tweaking logging again, making everything consistent

- backends/postgres/postgres_backend.go
Fixes https://github.com/acaloiaro/neoq/issues/112
Encode passwords so that puncuation characters including `:` and `@` are allowed in passwords.
> URL encode password

- backends/postgres/migrations/20240302172413_make_fingerprints_unique_to_each_queue.up.sql
As mentioned in #119, fingerprints should be unique to each queue, not globally.
> feat: Make fingerprint unique to each queue

- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
This PR updates the parsing and formatting of the URI that is used when applying migrations and adds tests for sample input connStrings
As of 94d7d68539b6980cece521b428733f6c344bc268, using a connString with a non-default port number will ignore the custom port and default to `5432` in `PgBackend.initializeDB` when attempting to run migrations. The current connString formatting code will read `pgxCfg.Host` but not `pgxCfg.Port` when generating the new connString
- `postgresq://localhost:5433/neoq?sslmode=disable` - Example input connString
- `postgresq://localhost/neoq?sslmode=disable&x-migrations-table=neoq_schema_migrations` - connString that is actually used by PgBackend to try to apply migrations, note the default `5432` port number will be used since it's not specified …
> feat: Update migrations postgres URI parsing and add tests

- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
> Fix an infinite loop when jobs are scheduled past their deadline 

- backends/memory/memory_backend.go
- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
- backends/redis/redis_backend.go
- backends/redis/redis_backend_test.go
- gomod2nix.toml
- handler/handler.go
- neoq.go
- neoq_test.go
Allows an optional reocvery callback function to be specified when errors occur. This allows custom behavior to be provided by neoq users when errors occur, e.g. for error reporting and metrics collection.
> feat: add support for recovery callbacks

- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
- gomod2nix.toml
- neoq.go
The previous release attempted to fix an issue where, when LISTEN connections drop and reconnect, some job announcements might be missed.
This fix reduces the number of connections required to do so.
> fix: fix execessive connection counts for monitoring pending jobs

- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
Instead of passing a single connection into the pending job processor,
use the connection pool to pull a new connection on every loop, releasing
it after every use.
> feat: make pendings job processing resilient to connection loss

- .github/workflows/golangci-lint.yml
- .github/workflows/test.yml
- .golangci.yaml
- backends/memory/memory_backend.go
- backends/memory/memory_backend_test.go
- backends/postgres/postgres_backend.go
- backends/postgres/postgres_backend_test.go
- backends/redis/redis_backend.go
- flake.lock
- flake.nix
- go.mod
- go.sum
- gomod2nix.toml
- handler/handler.go
- logging/logging.go
- neoq.go
There could be a condition where jobs were added to a queue that is not longer being watched,
yet the jobs in those queues would continue appearing in the pending job list because
the query to get pending jobs did not filter by queues being watched.
> fix: unprocessed jobs from unwatched queues block watched queues
